on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: curl -I -X GET https://spotbugs.github.io/eclipse-latest/plugins/com.github.spotbugs.plugin.eclipse_4.2.1.202101130102-63668db.jar
